# Generated by Django 4.2.14 on 2024-12-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedReportsHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seq', models.CharField(db_column='Sequence', max_length=6)),
                ('fosa', models.CharField(db_column='Fosa', max_length=248)),
                ('start_date', models.CharField(blank=True, db_column='startDate', null=True)),
                ('end_date', models.CharField(blank=True, db_column='endDate', null=True)),
            ],
            options={
                'db_table': 'tblPrintedReportsHistory',
            },
        ),
    ]
