# Generated by Django 4.2.19 on 2025-05-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcomores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printedreportshistory',
            name='end_date',
            field=models.CharField(blank=True, db_column='endDate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printedreportshistory',
            name='start_date',
            field=models.CharField(blank=True, db_column='startDate', max_length=100, null=True),
        ),
    ]
